remote_theme: pmarsceill/just-the-docs
---
layout: default
title: bitpaint
description: welcome to my website
nav_order: 0
---

footer_content: "Twitter: <a href=\"https://twitter.com/BITPAINTclub\">@bitpaintclub</a>"