remote_theme: pmarsceill/just-the-docs
---
layout: default
title: bitpaint
description: welcome to my website
nav_order: 0
---
aux_links:
  "Twitter":
    - "//twitter.com/BITPAINTCLUB"
aux_links_new_tab: true
