remote_theme: pmarsceill/just-the-docs
---
layout: default
title: bitpaint
description: welcome to my website
nav_order: 0

aux_links:
  "Follow me on Twitter":
    - "//twitter.com/BITPAINTCLUB"
aux_links_new_tab: false
---